name: ggosss2026
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - xarray
  - netcdf4
  - dask
  - matplotlib
  - cartopy
  - cmocean
  - gsw
  - jupyterlab
  - ipywidgets
  - scikit-learn
  - copernicusmarine
  - pip
